FROM node:lts-alpine
ENV NODE_ENV=development
WORKDIR /usr/src/app
COPY ["package.json", "package-lock.json*", "./"]
RUN npm install --silent
COPY ./src ./src
COPY ./public ./public
EXPOSE 3000
CMD ["npm", "run", "watch"]
